import { writeFile } from 'node:fs/promises'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { HunspellReader } from 'hunspell-reader'

export function normalizeDictionaryWord(value) {
  // Reject sharp S before uppercasing, which would otherwise turn it into SS.
  const word = value.normalize('NFC')
  if (!/^[a-zA-ZÄÖÜäöü]{5}$/.test(word)) return null
  return word.toUpperCase()
}

export async function generateWords() {
  const source = new URL('./dictionaries/de_DE_frami', import.meta.url)
  const reader = await HunspellReader.createFromFiles(`${fileURLToPath(source)}.aff`, `${fileURLToPath(source)}.dic`)
  // The reader decodes SET ISO8859-1, consumes flags/metadata, expands affixes,
  // and excludes forbidden, NEEDAFFIX-only, and compound-only forms.
  const accepted = new Set()
  for (const entry of reader) {
    const word = normalizeDictionaryWord(entry)
    if (word) accepted.add(word)
  }
  const words = [...accepted].sort()
  const output = '// Generated by npm run generate:words. Do not edit manually.\n'
    + '// Source: LibreOffice/dictionaries de/de_DE_frami (GPL-2.0-only OR GPL-3.0-only).\n'
    + '// Provenance and licenses: scripts/dictionaries/README.md\n'
    + `export const acceptedWords = new Set<string>(${JSON.stringify(words, null, 2)});\n`
  await writeFile(new URL('../src/data/acceptedWords.ts', import.meta.url), output)
  console.log(`Generated ${words.length} unique five-letter German words.`)
  return words
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await generateWords()
